dtb-$(CONFIG_ARCH_TEGRA) += tegra132-norrin.dtb
dtb-$(CONFIG_ARCH_TEGRA) += tegra210-p2371-0000.dtb
dtb-$(CONFIG_ARCH_TEGRA) += tegra210-p2371-2180.dtb
dtb-$(CONFIG_ARCH_TEGRA) += tegra210-p2571.dtb

always		:= $(dtb-y)
clean-files	:= *.dtb
